Description: A Load Balancer template CAC Week 2 assignment 1

Resources:

  CACW2A1LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: CACW2A1LoadBalancer
      Scheme: internet-facing
      SecurityGroups: 
        - !ImportValue BaseStack:SecurityGroup
      # SubnetMappings: 
      #   - !ImportValue BaseStack:MyFirstSubnet
      #   - !ImportValue BaseStack:MySecondSubnet
      Subnets: 
        - !ImportValue BaseStack:MyFirstSubnet
        - !ImportValue BaseStack:MySecondSubnet
      Tags: 
        - Key: Name
          Value: CACW2A1LoadBalancer

  TargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TargetGroup1
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !ImportValue InstancesStack:Instance1
          Port: 80
        - Id: !ImportValue InstancesStack:Instance2
          Port: 80
      VpcId: !ImportValue BaseStack:VPC

  Listener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroup1
      LoadBalancerArn: !Ref CACW2A1LoadBalancer
      Port: 80
      Protocol: HTTP

  