#   8 888888888o.      8 8888888888     d888888o.       ,o888888o.    8 888888888o.    8 8888 8 888888888o 8888888 8888888888  8 8888     ,o888888o.     b.             8
#   8 8888    `^888.   8 8888         .`8888:' `88.    8888     `88.  8 8888    `88.   8 8888 8 8888    `88.     8 8888        8 8888  . 8888     `88.   888o.          8
#   8 8888        `88. 8 8888         8.`8888.   Y8 ,8 8888       `8. 8 8888     `88   8 8888 8 8888     `88     8 8888        8 8888 ,8 8888       `8b  Y88888o.       8
#   8 8888         `88 8 8888         `8.`8888.     88 8888           8 8888     ,88   8 8888 8 8888     ,88     8 8888        8 8888 88 8888        `8b .`Y888888o.    8
#   8 8888          88 8 888888888888  `8.`8888.    88 8888           8 8888.   ,88'   8 8888 8 8888.   ,88'     8 8888        8 8888 88 8888         88 8o. `Y888888o. 8
#   8 8888          88 8 8888           `8.`8888.   88 8888           8 888888888P'    8 8888 8 888888888P'      8 8888        8 8888 88 8888         88 8`Y8o. `Y88888o8
#   8 8888         ,88 8 8888            `8.`8888.  88 8888           8 8888`8b        8 8888 8 8888             8 8888        8 8888 88 8888        ,8P 8   `Y8o. `Y8888
#   8 8888        ,88' 8 8888        8b   `8.`8888. `8 8888       .8' 8 8888 `8b.      8 8888 8 8888             8 8888        8 8888 `8 8888       ,8P  8      `Y8o. `Y8
#   8 8888    ,o88P'   8 8888        `8b.  ;8.`8888    8888     ,88'  8 8888   `8b.    8 8888 8 8888             8 8888        8 8888  ` 8888     ,88'   8         `Y8o.`
#   8 888888888P'      8 888888888888 `Y8888P ,88P'     `8888888P'    8 8888     `88.  8 8888 8 8888             8 8888        8 8888     `8888888P'     8            `Yo
Description: This is Stack 02 of Cloud Engineering\Cloud Automation Concepts\Assessment 01 | EFSStack | This CloudFormation stack deploys an Elastic File System and mount targets to facilitate daily logs storage. 










#   8 888888888o.   8 8888888888     d888888o.       ,o888888o.     8 8888      88 8 888888888o.      ,o888888o.    8 8888888888     d888888o.
#   8 8888    `88.  8 8888         .`8888:' `88.  . 8888     `88.   8 8888      88 8 8888    `88.    8888     `88.  8 8888         .`8888:' `88.
#   8 8888     `88  8 8888         8.`8888.   Y8 ,8 8888       `8b  8 8888      88 8 8888     `88 ,8 8888       `8. 8 8888         8.`8888.   Y8
#   8 8888     ,88  8 8888         `8.`8888.     88 8888        `8b 8 8888      88 8 8888     ,88 88 8888           8 8888         `8.`8888.
#   8 8888.   ,88'  8 888888888888  `8.`8888.    88 8888         88 8 8888      88 8 8888.   ,88' 88 8888           8 888888888888  `8.`8888.
#   8 888888888P'   8 8888           `8.`8888.   88 8888         88 8 8888      88 8 888888888P'  88 8888           8 8888           `8.`8888.
#   8 8888`8b       8 8888            `8.`8888.  88 8888        ,8P 8 8888      88 8 8888`8b      88 8888           8 8888            `8.`8888.
#   8 8888 `8b.     8 8888        8b   `8.`8888. `8 8888       ,8P  ` 8888     ,8P 8 8888 `8b.    `8 8888       .8' 8 8888        8b   `8.`8888.
#   8 8888   `8b.   8 8888        `8b.  ;8.`8888  ` 8888     ,88'     8888   ,d8P  8 8888   `8b.     8888     ,88'  8 8888        `8b.  ;8.`8888
#   8 8888     `88. 8 888888888888 `Y8888P ,88P'     `8888888P'        `Y88888P'   8 8888     `88.    `8888888P'    8 888888888888 `Y8888P ,88P'
Resources:

  #DO = Dependent on
  #Par = Parameter
  #Imp = Imported parameter

  #Description: This is a Security Group, this is used by the EFS file system and allows all incomming tcp packets from port 2049 (Used for accessing the mount targets) 
  #             and allows all outgoing packets from all ports.
  CACAA1EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This security groups allows incoming connection to port 2049
      GroupName: CACAA1EFSSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: CACAA1EFSSecurityGroup
      VpcId: !ImportValue BaseStack:VPC                                   #Imp: BaseStack:VPC                       (The VPC imported from the BaseStack)

  #Description: This is the EFS File System, this is configgered to use bursting throughput which means the maximum amount of data troughput scales with the amount of
  #             data stored but the minimum troughput is 100 MiB/s.
  CACAA1EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      ThroughputMode: bursting
  
  #Description: This is a EFS Mount Tagret, this will be created in the first of the two public subnets functioning as a connection to the EFS file system, 
  #             allowing the EFS to be accessed by instances in that subnet, in this case the mount target will be used by the webservers to stor log files.
  CACAA1EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref CACAA1EFSFileSystem                              #DO: CACAA1EFSFileSystem                  (The EFS File System)
      SecurityGroups: 
        - !Ref CACAA1EFSSecurityGroup                                     #DO: CACAA1EFSSecurityGroup               (The security group for the Elastic File System)
      SubnetId: !ImportValue BaseStack:PublicSubnet1                      #Imp: BaseStack:PublicSubnet1             (The first public subnet imported from the BaseStack)

  #Description: This is a EFS Mount Tagret, this will be created in the second of the two public subnets functioning as a connection to the EFS file system, 
  #             allowing the EFS to be accessed by instances in that subnet, in this case the mount target will be used by the webservers to stor log files.
  CACAA1EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref CACAA1EFSFileSystem                              #DO: CACAA1EFSFileSystem                  (The EFS File System)
      SecurityGroups: 
        - !Ref CACAA1EFSSecurityGroup                                     #DO: CACAA1EFSSecurityGroup               (The security group for the Elastic File System)
      SubnetId: !ImportValue BaseStack:PublicSubnet2                      #Imp: BaseStack:PublicSubnet2             (The second public subnet imported from the BaseStack)









                                                                                                              
#       ,o888888o.     8 8888      88 8888888 8888888888 8 888888888o   8 8888      88 8888888 8888888888 d888888o.   
#    . 8888     `88.   8 8888      88       8 8888       8 8888    `88. 8 8888      88       8 8888     .`8888:' `88. 
#   ,8 8888       `8b  8 8888      88       8 8888       8 8888     `88 8 8888      88       8 8888     8.`8888.   Y8 
#   88 8888        `8b 8 8888      88       8 8888       8 8888     ,88 8 8888      88       8 8888     `8.`8888.     
#   88 8888         88 8 8888      88       8 8888       8 8888.   ,88' 8 8888      88       8 8888      `8.`8888.    
#   88 8888         88 8 8888      88       8 8888       8 888888888P'  8 8888      88       8 8888       `8.`8888.   
#   88 8888        ,8P 8 8888      88       8 8888       8 8888         8 8888      88       8 8888        `8.`8888.  
#   `8 8888       ,8P  ` 8888     ,8P       8 8888       8 8888         ` 8888     ,8P       8 8888    8b   `8.`8888. 
#    ` 8888     ,88'     8888   ,d8P        8 8888       8 8888           8888   ,d8P        8 8888    `8b.  ;8.`8888 
#       `8888888P'        `Y88888P'         8 8888       8 8888            `Y88888P'         8 8888     `Y8888P ,88P' 
Outputs:
  
  #Description: This outputs a reference to the SecurityGroup used by the EFS.
  #This value is used in the stacks:
  # -
  EFSSecurityGroupRef:
    Description: Reference to the security group for EFS
    Value: !Ref CACAA1EFSSecurityGroup
    Export:
      Name: EFSStack:EFSSecurityGroup
  
  #Description: This outputs a reference to the Elastic File System.
  #This value is used in the stacks:
  # -WebStack
  # -
  EFSFileSystemRef:
    Description: Reference to the elastic file system 
    Value: !Ref CACAA1EFSFileSystem
    Export:
      Name: EFSStack:EFSFileSystem

  #Description: This outputs a reference to the EFS Mount Target in the first of the four subnets and the first of the two public subnets.
  #This value is used in the stacks:
  # -
  EFSMountTarget1Ref:
    Description: Reference to the first mount target public subnet 1
    Value: !Ref CACAA1EFSMountTarget1
    Export:
      Name: EFSStack:EFSMountTarget1
  
  #Description: This outputs a reference to the EFS Mount Target in the second of the four subnets and the second of the two public subnets.
  #This value is used in the stacks:
  # -
  EFSMountTarget2Ref:
    Description: Reference to the second mount target public subnet 2
    Value: !Ref CACAA1EFSMountTarget2
    Export:
      Name: EFSStack:EFSMountTarget2