#This file is already in a git repo and will not be called from here
#The file is located here: https://github.com/BFL-Psycho/cac-aa2-covid-services.git
version: '3.8'

services:
   broad-covid19-dashboard:
     image: covid-dashboard:latest
     ports:
        - "8080:80"

   nhs-covid19-registration-form:
     image: covid-form:latest
     ports:
       - "5000:5000"