#This file is already in a git repo and will not be called from here
#The file is located here: https://github.com/BFL-Psycho/cac-aa2-covid-services.git
version: "3.8"

services:
  #Description: This makes the docker workers deploy the dockerfile that will setup a webserver that hosts the Covid dashbaord.
  broad-covid19-dashboard:
    image: covid-dashboard:latest
    ports:
      - "80:80"
    deploy:
      mode: global # this will deploy service automatically on all the worker nodes, also the new joiners
      placement:
        constraints:
          - node.role == worker

  #Description: This makes the docker workers deploy the dockerfile that will setup a webserver that hosts NHS covid registration form.
  nhs-covid19-registration-form:
    image: covid-form:latest
    ports:
      - "5000:80"
    deploy:
      mode: global # this will deploy service automatically on all the worker nodes, also the new joiners
      placement:
        constraints:
          - node.role == worker
