Description: This stack contains an ECR (Elastic Container Repository)

Parameters: 

  CovidDashboardECRName:
    Description: Provide a name for Elastic Container Repository 
    Type: String
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    Default: cac-aa2-covid-dashboard-ecr

  CovidRegistrationFormECRName:
    Description: Provide a name for Elastic Container Repository 
    Type: String
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    Default: cac-aa2-covid-form-ecr

Resources:

  CACAA2ECRPrivateLinkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: This security groups allows 443 (HTTPS) which is required for the ECR PrivateLink #Refer to https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-api-error-ecr/
      GroupName: CACAA2ECRPrivateLinkSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue BaseStack:VPC
      Tags: 
        - Key: Name
          Value: CACAA2ECRPrivateLinkSecurityGroup

  #This endpoint is used for calls to the Amazon ECR API. API actions such as DescribeImages and CreateRepositories go to this endpoint.  
  #https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html      
  CACAA2ECRVPCEndpointAPI:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PrivateDnsEnabled: false
      SecurityGroupIds: 
        - !Ref CACAA2ECRPrivateLinkSecurityGroup
      ServiceName: com.amazonaws.us-east-1.ecr.api
      SubnetIds: 
        - !ImportValue BaseStack:PublicSubnet1
        - !ImportValue BaseStack:PublicSubnet2
      VpcEndpointType: Interface
      VpcId: !ImportValue BaseStack:VPC

  #This endpoint is used for the Docker Registry APIs. Docker client commands such as push and pull use this endpoint. 
  #https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html   
  CACAA2ECRVPCEndpointDKR:
      Type: AWS::EC2::VPCEndpoint
      Properties: 
        PrivateDnsEnabled: true
        SecurityGroupIds: 
          - !Ref CACAA2ECRPrivateLinkSecurityGroup
        ServiceName: com.amazonaws.us-east-1.ecr.dkr
        SubnetIds: 
          - !ImportValue BaseStack:PublicSubnet1
          - !ImportValue BaseStack:PublicSubnet2
        VpcEndpointType: Interface
        VpcId: !ImportValue BaseStack:VPC

  CACAA2CovidDashboardECR:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties: 
      RepositoryName: !Ref CovidDashboardECRName
      # RepositoryPolicyText: # this policy doesn't work, need to think of something else
      #   Version: '2012-10-17'
      #   Id: CACAA2ECRAccessPolicy
      #   Statement:
      #   - Sid: IPAllow
      #     Effect: Allow
      #     Action: ecr:*
      #     Resource: "*"
      #     Condition:
      #       ForAnyValue:IpAddress:
      #         aws:SourceIp:
      #         - 10.0.1.0/24 #Maybe replace with CIDR vars from BaseStack
      #         - 10.0.2.0/24
      #         - 10.0.51.0/24
      #         - 10.0.52.0/24     
      Tags: 
        - Key: Name
          Value: CACAA2CovidDashboardECR

  CACAA2CovidRegistrationFormECR:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties: 
      RepositoryName: !Ref CovidRegistrationFormECRName
      # RepositoryPolicyText: # this policy doesn't work, need to think of something else
      #   Version: '2012-10-17'
      #   Id: CACAA2ECRAccessPolicy
      #   Statement:
      #   - Sid: IPAllow
      #     Effect: Allow
      #     Action: ecr:*
      #     Resource: "*"
      #     Condition:
      #       ForAnyValue:IpAddress:
      #         aws:SourceIp:
      #         - 10.0.1.0/24 #Maybe replace with CIDR vars from BaseStack
      #         - 10.0.2.0/24
      #         - 10.0.51.0/24
      #         - 10.0.52.0/24     
      Tags: 
        - Key: Name
          Value: CACAA2CovidRegistrationFormECR
  
#Provide exports

#Export ECR Urls